-- Copyright (C) 2026 Pierre Ardoin <developpeur@lesmetiersdubatiment.fr>

CREATE TABLE IF NOT EXISTS llx_powerplantpv_product_battery(
	rowid integer AUTO_INCREMENT PRIMARY KEY NOT NULL,
	fk_product integer NOT NULL,
	entity integer NOT NULL DEFAULT 1,
	storage_type varchar(32) NOT NULL DEFAULT 'BATTERY_MODULE',
	battery_family varchar(128),
	chemistry varchar(32),
	nominal_energy double(24,8),
	usable_energy double(24,8),
	capacity_ah double(24,8),
	nominal_voltage double(24,8),
	voltage_min double(24,8),
	voltage_max double(24,8),
	dod double(6,3),
	max_charge_power double(24,8),
	max_discharge_power double(24,8),
	peak_charge_power double(24,8),
	peak_discharge_power double(24,8),
	peak_duration double(24,8),
	max_charge_current double(24,8),
	max_discharge_current double(24,8),
	roundtrip_efficiency_dc double(6,3),
	roundtrip_efficiency_ac double(6,3),
	cycle_life integer,
	cycle_end_capacity double(6,3),
	warranty_years integer,
	warranty_cycles integer,
	warranty_throughput double(24,8),
	min_modules integer,
	max_modules integer,
	max_parallel_systems integer,
	operating_temperature_min double(24,8),
	operating_temperature_max double(24,8),
	storage_temperature_min double(24,8),
	storage_temperature_max double(24,8),
	humidity_min double(6,3),
	humidity_max double(6,3),
	max_altitude integer,
	ip_rating varchar(64),
	corrosion_class varchar(64),
	cooling varchar(128),
	noise_comparator varchar(3),
	noise double(24,8),
	installation_location varchar(32),
	mounting varchar(128),
	datec datetime,
	tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat integer,
	fk_user_modif integer
) ENGINE=innodb;
